#pragma once

#ifdef __FASTEST_RUN__

#define FASTEST_ASSERT_EQ 0x1
#define FASTEST_ASSERT_NEQ 0x2
#define FASTEST_ASSERT_GT 0x4
#define FASTEST_ASSERT_GE 0x8
#define FASTEST_ASSERT_LT 0x10
#define FASTEST_ASSERT_LE 0x20

#define FASTEST_ERROR 0x40
#define FASTEST_WARNING 0x80
#define FASTEST_LOG 0x100

#define FASTEST_TIME_S 0x200
#define FASTEST_TIME_MS 0x400
#define FASTEST_TIME_US 0x800
#define FASTEST_TIME_NS 0x1000

#define FASTEST_MEM_TRACK 0x2000

#endif // __FASTEST_RUN__
